version: '3'
services:
  webproxy:
    image: traefik
    command: --web --docker --docker.domain=test.boucke.be --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    
#    run -v $PWD/src/traefik/traefik.toml:/etc/traefik/traefik.toml -v $PWD/src/traefik/ssl:/etc/ssl traefik -l DEBUG
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-ubuntu
    container_name: webserver    
    volumes:
      - ./content/:/var/www/html/test1.test.boucke.be
      - ./content/:/var/www/html/test2.test.boucke.be
      - ./content/:/var/www/html/test3.test.boucke.be
      - ./letsencrypt/:/etc/letsencrypt
    labels:
      - "traefik.frontend.rule=Host:test1.test.boucke.be"
      - "traefik.port=80,443" 
  caddy:
    image: abiosoft/caddy
        
    
    