version: '3'
services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile-ubuntu
    container_name: webserver    
    volumes:
      - ./content/:/var/www/html
      - ./letsencrypt/:/etc/letsencrypts
    ports:
      - "80:80"
      - "443:443"